/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.17).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package julien.rod.fibonacci.api.endpoints;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-11-10T14:22:17.308Z")

@Api(value = "fibonacci", description = "the fibonacci API")
@RequestMapping(value = "/api")
public interface FibonacciApi {

    @ApiOperation(value = "", nickname = "askValMax", notes = "allow user to ask for a fibonacci with a defined max value", response = Object.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Fibonacci", response = Object.class) })
    @RequestMapping(value = "/fibonacci",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Object> askValMax(@ApiParam(value = "" ,required=true )  @Valid @RequestBody String maxVal);

}
